version: "3"

services:

 nginx:
   image: nginx:alpine
   container_name: ${APP_NAME}_nginx
   restart: unless-stopped
   volumes:
     - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}:delegated
     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
     - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:delegated
     - ./docker/nginx/ssl/:/etc/nginx/ssl/:delegated
   ports:
     - ${NGINX_80}:80
     - ${NGINX_443}:443
   depends_on:
     - app
   networks:
     - app-network


# Docker Networks
networks:
 app-network:
   driver: bridge
