version: "3"

services:
    client:
        image: nginx
        ports:
          - ${NGINX_80}:80
          - ${NGINX_443}:443
        volumes:
            - ./www:/usr/share/nginx/html
#            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
#            - ./docker/nginx/ssl/:/etc/nginx/ssl/
