version: "3"

services:
#    client:
#        image: nginx
#        ports:
#          - ${NGINX_80}:80
#          - ${NGINX_443}:443
#        volumes:
#            - ./www:/usr/share/nginx/html
apache:
    image: 'bitnami/apache:latest'
    ports:
      - ${NGINX_80}:8080
      - ${NGINX_443}::443
    volumes:
      - ./www:/app
